dcos/dcos-mesos-modules

- Makefile.am
- configure.ac
- journald/journald.hpp
- journald/lib_journald.cpp
- journald/lib_journald.hpp
This reverts commit 11d8b8fbab3f98112b403059446338a8a3a81190.
> Revert "Downgrade code to a pre-1.1.0 version of Mesos."

- journald/lib_journald.cpp
- tests/journald_tests.cpp
When you pass the Docker Containerizer a Task/Executor ID with a
colon in the ID, the sandbox path will be changed from the
canonical path to a symlink.  This symlink is missing most
of the information of the canonical path.
The journald logger was relying on the sandbox path to derive
the Agent/Container IDs.  This commit changes the logic to only
add Agent/Container ID labels when the fields can be derived,
instead of CHECK-ing that the fields are present.
Internal JIRA: https://jira.mesosphere.com/browse/CORE-1062
> Fixed a CHECK failure when using Docker Containerizer.

- tests/journald_tests.cpp
> Followed Mesos fetcher signature change.

- overlay/agent.cpp
- overlay/master.cpp
- tests/overlay_tests.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/19)
> Add virtual networks after a master restart.

- bootstrap
- support/cpplint.py
- support/hooks/commit-msg
- support/hooks/post-rewrite
- support/hooks/pre-commit
- support/mesos-split.py
- support/mesos-style.py
Currently we don't have any hooks installed to make sure that we are following the Mesos code-style. Adding this infrastructure (copied over from Mesos) in order provide hooks to do some basic linting of the cpp and hpp files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/18)
> Add hooks for checking `mesos-style` in this code-base.

- m4/libtool.m4
- m4/ltoptions.m4
- m4/ltsugar.m4
- m4/ltversion.m4
- m4/lt~obsolete.m4
Ran `./bootstrap` on a more up-to-date autoconf and added the resulting file modifications.
> Rerun bootstrap and update m4 files.

- tests/main.cpp
- tests/overlay_tests.cpp
Fixed tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/31)
> Fixing compilation errors due to changes to the `logging` interface.

- overlay/agent.cpp
- overlay/master.cpp
- overlay/network.hpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/20)
> Ipv6 support

- common/shell.hpp
- journald/lib_journald.cpp
- journald/lib_journald.hpp
- tests/dockercfg_tests.cpp
- tests/journald_tests.cpp
This patch set also fixed some test issues.
> Updated the journald logger to the latest logger interface.

- journald/lib_journald.cpp
This is the followup fix for potential FD leak issue after https://issues.apache.org/jira/browse/MESOS-9151 was fixed in DC/OS.
> Updated the ::pipe() system calls to pipe2 in lib_journald.

- journald/lib_journald.cpp
(cherry picked from commit 37e85c4ab92b9c8918e8aae948dd4b9469358688)
> [1.12][Backport] Updated the ::pipe() system calls to pipe2 in lib_journald.

- journald/lib_journald.cpp
(cherry picked from commit 37e85c4ab92b9c8918e8aae948dd4b9469358688)
> [1.11][Backport] Updated the ::pipe() system calls to pipe2 in lib_journald.

- overlay/agent.cpp
- tests/overlay_tests.cpp
jira: https://jira.mesosphere.com/browse/DCOS-43865
> [backport] Support coreos 1800.7.0

- Makefile.am
- configure.ac
- tests/journald_tests.cpp
Fixes [DCOS_OSS-4485](https://jira.mesosphere.com/browse/DCOS_OSS-4485) to allow for maintaining the 1.11 branch for future releases.
> Backported build fixes from master into 1.11.

- tests/dockercfg_tests.cpp
- tests/journald_tests.cpp
Mostly a cherry-pick of 31c4d688f9a571b103e73d8ea7be4af02ae109ac without including changes to common/shell.hpp as those are not test related.
> Backported fixes for tests that were not prepared for TASK_STARTING.

- overlay/agent.cpp
- overlay/master.cpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
JIRA: https://jira.mesosphere.com/browse/DCOS-40539
DC/OS PR: https://github.com/dcos/dcos/pull/3939
> dcos6 interface shown in the UI even when enable_ipv6 was set to false

- overlay/agent.cpp
- overlay/master.cpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
JIRA: https://jira.mesosphere.com/browse/DCOS-40539
DC/OS PR: https://github.com/dcos/dcos/pull/4115
> [1.12] dcos6 interface shown in the UI even when enable_ipv6 was set to false

- overlay/agent.cpp
- overlay/master.cpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
JIRA: https://jira.mesosphere.com/browse/DCOS-40539
DC/OS PR: https://github.com/dcos/dcos/pull/4116
> [1.11] dcos6 interface shown in the UI even when enable_ipv6 was set to false

- overlay/master.cpp
- overlay/messages.proto
JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-4575
> Add replicated log timeout.

- .github/pull_request_template.md
[DCOS-46995](https://jira.mesosphere.com/browse/DCOS-46995) - Provide a PR template for the modules.
> Introducing a PR template to enable automated CHANGELOG generation.

- journald/journald.cpp
This change fixes the issue that pod cannot be launched with non-root user because `mesos-journald-logger` has no permission to access container's `stdout`/`stderr` in absolute path.
These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
- [DCOS-47501](https://jira.mesosphere.com/browse/DCOS-47501) Pod cannot be launched with non-root user.
> Changed the working directory before changing user.

- overlay/agent.cpp
- overlay/master.cpp
- overlay/messages.proto
- overlay/supervisor.hpp
- tests/overlay_tests.cpp
Backport of #98 and #82 to 1.12.
These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
- [DCOS_OSS-4575](https://jira.mesosphere.com/browse/DCOS_OSS-4575) Add timeout while trying to recover overlay
> [1.12] Master overlay module got stuck in RECOVERING state

- journald/README.md
- journald/journald.cpp
- tests/journald_tests.cpp
This is a cherry-pick of commits from #107 and #109.  The README changes are not strictly necessary, but would make the 1.13 branch more consistent.
[DCOS-52803](https://jira.mesosphere.com/browse/DCOS-52803) Enrich Fluentbit logging with Mesos metadata.
> [1.13] Cherry-pick of Fluentbit support in logger module.

- journald/journald.cpp
- journald/journald.hpp
- journald/lib_journald.cpp
- journald/lib_journald.hpp
- tests/journald_tests.cpp
This opens up this module to being compiled/run on Windows.
The main change is #ifdef-ing anything related to journald,
which does not exist on Windows.
Modules are not yet supported on Windows, so there are no real
build changes yet.
[DCOS-58622](https://jira.mesosphere.com/browse/DCOS-58622) Consider porting the fluentbit container logger module to Windows.
> Tech Preview: Windows: ContainerLogger: Partitioned Linux-specific bits from module.

- metrics/isolator.hpp
[DCOS_OSS-5645](https://jira.mesosphere.com/browse/DCOS_OSS-5645) Metrics module breaks DC/OS tests.
> Fixed newly introduced bug in metrics parameter parsing.

- overlay/master.cpp
It is a fix of bug that could lead to double-allocation of the same VTEP IP address to different agents.
[DCOS_OSS-5626](https://jira.mesosphere.com/browse/DCOS_OSS-5626) Mesos overlay master must reserve all VTEP IP addresses of all overlays of all agents upon recovering from the replicated log.
> [1.13] Reserve all agent VTEP IPs upon recovering from replicated log.

- overlay/master.cpp
It is a fix of bug that could lead to double-allocation of the same VTEP IP address to different agents.
[DCOS_OSS-5626](https://jira.mesosphere.com/browse/DCOS_OSS-5626) Mesos overlay master must reserve all VTEP IP addresses of all overlays of all agents upon recovering from the replicated log.
> [1.12] Reserve all agent VTEP IPs upon recovering from replicated log.

- journald/journald.cpp
I/O completion ports (IOCP) are the backbone of Mesos' implementation
of a native event loop on Windows.  It happens that IOCP cannot be
used with non-disk files, like the standard input/output handles.
Instead, we simply need to make blocking reads on STDIN.  Considering
what the logger binary needs to do, this is not a big demerit.
[DCOS-61896](https://jira.mesosphere.com/browse/DCOS-61896) GLOG_v=2 …
> Windows: Fixed reading of STDIN with the native event loop.

- CMakeLists.txt
- README.md
- cmake/Dependencies.cmake
- dockercfg/CMakeLists.txt
- journald/CMakeLists.txt
- journald/lib_journald.hpp
- logsink/CMakeLists.txt
- logsink/logsink.hpp
- metrics/isolator.hpp
- overlay/CMakeLists.txt
- overlay/agent.cpp
- overlay/agent.hpp
- tests/CMakeLists.txt
> Ported to cmake build system.

- CMakeLists.txt
- README.md
- common/shell.hpp
- journald/CMakeLists.txt
- journald/modules.json.cmake-in
- tests/CMakeLists.txt
- tests/common_tests.cpp
- tests/journald_tests.cpp
- tests/metrics_tests.cpp
https://jira.d2iq.com/browse/D2IQ-65487
> Fixed test cases for windows.
