- Makefile.am
- configure.ac
- logsink/logsink.cpp
- logsink/logsink.hpp
- logsink/modules.json.in
- tests/logsink_tests.cpp
The glog library exposes a `LogSink` interface which can be used to consume logs and direct them to some arbitrary location.  
This module simply prints the logs to a single configurable file.  (This is much simpler than glog's option of writing logs to a directory with some built-in log rotation and verbose log names.)
Logging to stderr is not affected.
> Adds an anonymous module which redirects glog output.

- overlay/agent.cpp
- overlay/agent.hpp
- tests/overlay_tests.cpp
* Restructured the overlay agent module so that we can expose the `agent::ManagerProcess` in unit-tests.
* Re-wrote the unit-tests to use `agent::ManagerProcess`.
> Restructure of the overlay agent module.

- journald/journald.cpp
- journald/journald.hpp
- journald/lib_journald.cpp
- journald/lib_journald.hpp
- journald/modules.json.in
- tests/journald_tests.cpp
This provides a backwards compatibility mode for the container logger.
In case the sandbox logs are still necessary, this adds a "destination_type" option which can pipe logs to both journald and the sandbox.
> Combined Logrotate logger functionality into journald logger.

- journald/lib_journald.cpp
- journald/lib_journald.hpp
This PR is dependent on https://reviews.apache.org/r/57121/
Once this review lands, we should merge this.
> Updated logger to include rename of ContainerLogger::SubprocessInfo.

- logsink/logsink.cpp
This sets the permissions on the log file generated by the logsink
module to: Read/Write for the owner of the file and Read for the group.
This does not change permissions on existing files.  But newly created log files will have the updated permissions.
JIRA: https://jira.mesosphere.com/browse/DCOS-12261
> Logsink: Removed read permissions on log file for "other users".

- Makefile.am
The `GMOCK_VERSION` has been deprecated in Mesos so needed to the tests
to use `GOOGLETEST_VERSION` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/15)
> Fixed compilation errors for `make check`.

- Makefile.am
Without this patch, the configure time setup of `enable-debug` as well as `enable-optimize` will not influence the build results.
> Updated Makefile.am to inherit `MESOS_CXXFLAGS` properly.

- journald/lib_journald.cpp
- journald/lib_journald.hpp
- tests/journald_tests.cpp
This adds a rather primitive limit to the number or size of
labels passed from tasks to the container logger companion
binary.  Once the JSON-ified size of labels surpasses a
configurable size, the module simply cuts off any more
arbitrary labels before proceeding with the logger module's
business as usual.
I would prefer to land this after #21 and #22 if possible.
> Added configurable limit to the size of labels passed in logger.

- m4/libtool.m4
- m4/ltoptions.m4
- m4/ltsugar.m4
- m4/ltversion.m4
- m4/lt~obsolete.m4
- overlay/agent.cpp
- overlay/master.cpp
- support/mesos-style.py
- tests/overlay_tests.cpp
* Fixed compilation error during to introduction of `State` variable in `ProcessBase`.
* Fixed linter errors in master.cpp and agent.cpp.
* Fixed linter to not check the license header since the license is already added as part of the GitHub repo. Also, the license checks were Mesos specific so didn't make sense to make it part of our linter.
* Had to add modified files from `libtool`/m4 directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos-mesos-modules/27)
> Fixed overlay compilation errors and workaround to UPID optimization

- journald/lib_journald.cpp
- tests/journald_tests.cpp
If a nested container is launched on a parent container after
restarting the agent (the parent container is launched prior to
restart), then the ExecutorInfo passed into the ContainerLogger
may be blank.  This means that fields that are normally required
such as FrameworkID and ExecutorID will be blank.
This includes one test which:
1. Launches a parent container (prints then sleeps)
2. Emulates an agent failover
3. Launches a nested container (prints then exits)
4. Checks that filtering by `AGENT_ID` shows parent+child messages
5. Checks that filtering by `FRAMEWORK_ID` only shows the parent message
```
sudo ./test-journald --gtest_filter="*ROOT_CGROUPS_LaunchThenRecoverThenLaunchNested" --gtest_repeat=100 --gtest_break_on_failure
```
> Fixed CHECK failure for one case with nested containers.

- overlay/agent.cpp
- overlay/master.cpp
Enables the contents of ZooKeeper configuration to be stored in a file instead of allowing only the configuration to be raw in the `MESOS_ZK` environment variable for masters and `MESOS_MASTER` for agents.
**DC/OS PR [dcos/pull/2468](https://github.com/dcos/dcos/pull/2468)**
> [1.11] Allows ZooKeeper configuration to be stored in files.

- overlay/agent.cpp
- overlay/master.cpp
Enables the contents of ZooKeeper configuration to be stored in a file instead of allowing only the configuration to be raw in the `MESOS_ZK` environment variable for masters and `MESOS_MASTER` for agents.
**DC/OS PR [dcos:pull/2469](https://github.com/dcos/dcos/pull/2469)**
> Allows ZooKeeper configuration to be stored in files.

- overlay/agent.cpp
- overlay/agent.hpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
Currently, if there are multiple configuraton attempt failures for the overlay module running on the agent, when registered with the overlay module in the Master it leads to the overlay modules actor just giving up on the registration.
We need to test that the number of configuration attemtps are reset when master failover happens, i.e., if a master failover happens and number of config attempts is less than the number of attempts supported by the overlay module the number of config attempts should be reset and the overlay module should continue attempting to register.
JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-728
> Create testcase for Mesos master failover with DC/OS overlay modules

- Makefile.am
- common/shell.hpp
- overlay/agent.cpp
- overlay/messages.proto
- tests/common_tests.cpp
The overlay module currently shells out to docker in order to create and inspect docker networks. If the docker daemon hangs, or is unreachable this can end up blocking the overlay agent module. We therefore need to introduce timeouts to calls to the docker daemon and ensure that we handle the failure scenario correctly.
JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-695
> Introduce timeouts for calls to docker deamon in DC/OS overlay module

- overlay/master.cpp
- overlay/overlay.proto
- tests/overlay_tests.cpp
https://jira.mesosphere.com/browse/DCOS_OSS-1529
> DC/OS Config "dcos_overlay_mtu" can not be used for VTEP1024. VTEP1024's MTU is always greater(more than 54 bytes?) than "dcos_overlay_mtu" for vxlan overhead.
> Add MTU configuration for vtep1024

- Makefile.am
- configure.ac
DC/OS compiles Mesos with Libevent and SSL enabled, which means that `-DUSE_SSL_SOCKET` is defined during compilation time across all files.  This definition was missing in this modules repo, which leads to a subtle abort/segfault during tests:
```
[ RUN      ] DockerRemoveTest.VerifyRemoveDockerCfgHook
ABORT: (../../3rdparty/stout/include/stout/flags/flags.hpp:433): Attempted to add flag 'hostname' with incompatible type
*** Aborted at 1499293280 (unix time) try "date -d @1499293280" if you are using GNU date ***
PC: @     0x2b806a3607ef (unknown)
*** SIGABRT (@0x3e80000636d) received by PID 25453 (TID 0x2b8061116280) from PID 25453; stack trace: ***
@     0x556f73d34f0c _Abort()
@     0x2b8066c7fe05 _ZN5flags9FlagsBase3addIN5mesos8internal5slave5FlagsENSt7__cxx1112basic_stringIcSt11char_ …
```
> Fix segfault in tests and potential badness in general.

- overlay/agent.cpp
- overlay/master.cpp
- overlay/messages.proto
- tests/overlay_tests.cpp
more details can be found here https://jira.mesosphere.com/browse/COPS-3231. 
The issue happened during the upgrade from 1.10.x to 1.11.x wherein the ipv6 address was not added to an existing vtep interface which resulted in failure to configure ipv6 overlay on the agent. This patch fixes the issue by adding ipv6 address to an existing vtep interface.
During debugging of the above issue, it was discovered that ipv6 disable functionality was breaking the overlay module. Reason being, the overlay module doesn't support deletion of an existing overlay network. This patch also fixes that issue by introducing an `enable_ipv6` flag to provide ipv6 disable functionality. The default value of the flag is true i.e. ipv6 is enabled by default.
> This patch is to fix upgrade issues from DC/OS 1.10 to 1.11+

- overlay/agent.cpp
- overlay/master.cpp
- overlay/messages.proto
- tests/overlay_tests.cpp
1. Fixes the upgrade issue in which an ipv6 address wasn't getting added
to an existing vtep interface
2. Fixes master overlay module recovery upon disabling ipv6 after it was
enabled once
This is a cherry-pick of the commit https://github.com/dcos/dcos-mesos-modules/commit/e1c47cb157b0f5adac086568eccf183b3e814ee2
> Fixes couple of issues with ipv6 overlay implementation

- configure.ac
Mesos recently made it unnecessary to manually define
PICOJSON_USE_INT64 to use its stout/json.hpp header. For that they
move the definition into the header itself. We currently still manually
define this flag which leads to a (intentionally made fatal) warning
about a macro redefinition.
This patch removes our defintion.
This PR and description is taken from the corresponding EE PR: https://github.com/mesosphere/dcos-ee-mesos-modules/pull/273
> Removed unneeded picojson definition.

- overlay/agent.cpp
- overlay/agent.hpp
- overlay/messages.proto
Currently, host-local ipam cni plugin uses a persistent location
on the disk as its data dir where it keeps the information about
allocated IP addresses. This leads to orphan IP addresses if
the agent reboots. This patch moves the data dir to a tmpfs location
so that all the allocated IP addresses are recycled upon agent reboot.
jira ticket: DCOS_OSS-3750
> Adds dataDir in the host-local ipam configuration

- overlay/agent.cpp
- tests/overlay_tests.cpp
Docker isolates its networks by adding an explicit DROP iptables rules
for any cross communication. However, Overlay (which uses
docker network) allows seamless communication among Docker networks.
So, Overlay by-passes Docker isolation by adding an explicit RETURN
as the first iptables rule in the chain. However, due to a bug,
Overlay missed adding that rule if Docker network is already
present. This patch fixes that issue
jira ticket: DCOS_OSS-3697
> Fixes an issue with the iptables rules in Overlay

- overlay/agent.cpp
- tests/overlay_tests.cpp
Docker isolates its networks by adding an explicit DROP iptables rules
for any cross communication. However, Overlay (which uses
docker network) allows seamless communication among Docker networks.
So, Overlay by-passes Docker isolation by adding an explicit RETURN
as the first iptables rule in the chain. However, due to a bug,
Overlay missed adding that rule if Docker network is already
present. This patch fixes that issue
jira ticket: DCOS_OSS-3697
> [Backport][1.11] Fixes an issue with the iptables rules in overlay

- overlay/agent.cpp
- tests/overlay_tests.cpp
Docker isolates its networks by adding an explicit DROP iptables rules
for any cross communication. However, Overlay (which uses
docker network) allows seamless communication among Docker networks.
So, Overlay by-passes Docker isolation by adding an explicit RETURN
as the first iptables rule in the chain. However, due to a bug,
Overlay missed adding that rule if Docker network is already
present. This patch fixes that issue
jira ticket: DCOS_OSS-3697
> [Backport][1.10] Fixes an issue with the iptables rules in overlay

- Makefile.am
- configure.ac
- metrics/isolator.cpp
- metrics/isolator.hpp
- metrics/messages.proto
- metrics/modules.json.in
- tests/metrics_tests.cpp
This PR adds the new metrics isolator module. The module does the following:
* Hits the metrics service API during container launch to retrieve a metrics host/port
* Injects the retrieved host/port into the container's environment
> Add the metrics module.

- metrics/isolator.cpp
- metrics/messages.proto
- tests/metrics_tests.cpp
This PR addresses several issues in the metrics isolator module:
1) The module makes DELETE requests to the metrics service when debug containers are cleaned up, even though we do not make POST requests for those containers when they are launched.
2) There are a couple small typos in logging messages.
3) Some unused protobuf messages have not been removed.
> Fix issues in the metrics isolator module.

- overlay/agent.cpp
- tests/overlay_tests.cpp
Coreos 1800.7.0 comes with default docker version of 18.x which has modified its iptables CHAIN names from `DOCKER-ISOLATION` to `DOCKER-ISOLATION-STAGE-1` and `DOCKER-ISOLATION-STAGE-2` which broke mesos overlay module. This patch detects the CHAIN name before applying the iptables rule so that it could work for both old and newer docker versions.
jira: https://jira.mesosphere.com/browse/DCOS_OSS-3707
> fixes iptables rules to support coreos 1800.7.0

- overlay/agent.cpp
- tests/overlay_tests.cpp
Coreos 1800.7.0 comes with default docker version of 18.x which has modified its iptables CHAIN names from DOCKER-ISOLATION to DOCKER-ISOLATION-STAGE-1 and DOCKER-ISOLATION-STAGE-2 which broke mesos overlay module. This patch detects the CHAIN name before applying the iptables rule so that it could work for both old and newer docker versions.
jira: https://jira.mesosphere.com/browse/DCOS_OSS-3707
> [Backport] [1.11] fixes iptables rules to support coreos 1800.7.0

- overlay/agent.cpp
- tests/overlay_tests.cpp
Coreos 1800.7.0 comes with default docker version of 18.x which has modified its iptables CHAIN names from DOCKER-ISOLATION to DOCKER-ISOLATION-STAGE-1 and DOCKER-ISOLATION-STAGE-2 which broke mesos overlay module. This patch detects the CHAIN name before applying the iptables rule so that it could work for both old and newer docker versions.
jira: https://jira.mesosphere.com/browse/DCOS_OSS-3707
> [Backport] [1.12] fixes iptables rules to support coreos 1800.7.0

- metrics/isolator.cpp
- metrics/messages.proto
- tests/metrics_tests.cpp
This PR backports to 1.12 several fixes for the metrics isolator module to which have already landed in the master branch. See https://github.com/dcos/dcos-mesos-modules/pull/57
> Backport fixes for the metrics isolator.

- tests/journald_tests.cpp
This test was observed to be flaky, and this information
might be helpful to narrow down the root cause of the
flakiness.
> Add additional log output to 'ROOT_LogToJournald' test.

- journald/lib_journald.hpp
`ContainerLogger` interface does not currently use a
"prepare-recover-cleanup" pattern and hence neither allows
stateful loggers nor provides synchronization on container
termination.
> Added a comment around synchronization on container cleanup.

- tests/journald_tests.cpp
Due to the lack of synchronization between container logger cleanup and
task termination, a write to the task's stdout or stderr log might occur
after a terminal status update is sent.
To adjust a test's expectation without introducing synchronization, a
busy loop with a timeout is added to check for the expected log output.
[DCOS-46137](https://jira.mesosphere.com/browse/DCOS-46137) LoggingMode/JournaldLoggerTest.ROOT_LogToJournald is flaky.
>  Fixed flaky JournaldLoggerTest.ROOT_LogToJournald test.

- Makefile.am
- README.md
- configure.ac
- journald/journald.cpp
- journald/lib_journald.cpp
- tests/journald_tests.cpp
This is the JournaldContainerLogger version of https://issues.apache.org/jira/browse/MESOS-9564,
which seals logrotate configuration files into MemFDs instead of writing them into a container's sandbox.
This also disables custom logrotate options via environment variables, as intended by this issue: 
https://issues.apache.org/jira/browse/MESOS-9576
The DC/OS documentation affected will be updated here:
https://github.com/mesosphere/dcos-docs-site/pull/2079
These JIRA ticket(s) must be updated (ideally closed) in the …
> Journald logrotate configuration file sealing

- Vagrantfile
- overlay/master.cpp
- overlay/supervisor.hpp
- tests/overlay_tests.cpp
There are multiple issues with recovering mode in master overlay module.
1. There are no timeouts in any replicated log functions. I added timeout for `fetch()`in #82, but master modules still will get stuck if replicated log times out.
2. There are a bunch of `abort()` calls in `_recover()` function. It means that module can kill the whole mesos leader. Recently, we've seen mesos leader crash looping because of it.
3. `demote()` doesn't force agent re-registration or mesos re-election.
These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
- [DCOS_OSS-4575](https://jira.mesosphere.com/browse/DCOS_OSS-4575) Add timeout while trying to recover overlay
> Master overlay module got stuck in RECOVERING state

- Makefile.am
- README.md
- configure.ac
- journald/journald.cpp
- journald/lib_journald.cpp
- tests/journald_tests.cpp
This is the 1.12 cherry-pick of #103.  These changes applied cleanly.
[DCOS-47733](https://jira.mesosphere.com/browse/DCOS-47733) Disable modifications to container logger's custom logrotate options.
> [1.12] Journald logrotate configuration file sealing

- logsink/logsink.cpp
- logsink/logsink.hpp
This PR switches the FileSink in the logsink module to using the new LogSink interface added at https://issues.apache.org/jira/browse/MESOS-9687.
This finally solves the problem with zeroed microseconds in the logs which are written through this module:
https://jira.mesosphere.com/browse/DCOS-24365
Testing done: manually checked that there are microseconds in the DCOS built with this patch (build and DCOS integration tests: https://github.com/dcos/dcos/pull/4934) …
> Switched FileSink to the new LogSink interface (with usecs).

- journald/journald.cpp
- journald/journald.hpp
- journald/lib_journald.cpp
- journald/lib_journald.hpp
- journald/modules.json.in
- tests/journald_tests.cpp
This adds an option to pipe log output over TCP, presumably to a fluentbit server running at a specified address.  In order to configure this properly, the fluentbit IP/Port **must** be added to the module parameters.  And the output mode should probably be set to `fluentbit+logrotate`:
https://github.com/dcos/dcos/blob/master/gen/dcos-config.yaml#L390-L412
The unit test does not require fluentbit as the pipeline is really just a TCP dump of log lines (albeit wrapped in JSON objects).
These JIRA ticket(s) must be updated …
> Fluentbit integration

- journald/README.md
This expands the container logger documentation with some more tidbits about
the `fluentbit` mode and adds more notes about the existing modes.
> Updated container logger readme with new info about modes.

- journald/lib_journald.cpp
Perf traces from DC/OS agents running a considerable number of command
health checks showed that the agent spends a considerable amount of time
forking out processes to pipe the output of `DEBUG` containers to
journald.
`DEBUG` containers are mostly used by the default executor to run checks
and by operators using `dcos task exec` to run commands in interactive
sessions. The default executor already logs the output of the checks it
performs, and operators most probably don't expect the interactive
sessions logs to be sent to journald, so we decided to use sandbox
logging for `DEBUG` containers.
**Note**: This section is intended for robots. Titles supplied in this template will be used as CHANGELOG entries for this patch - consider diverting from the original JIRA subject to fit this …
> Made logging module use sandbox logging for DEBUG containers.

- journald/README.md
- journald/journald.cpp
- tests/journald_tests.cpp
This adds the same log metadata we currently add with `journald` logging, to `fluentbit` logging.  This includes tagging each line with various `*_ID`s and other labels found within a task's `ExecutorInfo`.
The README is adjusted to mention this.  Also, some existing behavior (`--max_label_payload_size`) is documented, which applies to both `journald` and `fluentbit` modes. …
> Added metadata tagging to fluentbit logging mode.

- journald/lib_journald.cpp
- tests/journald_tests.cpp
This is a followup commit for #108 which adds a test exercising the change.
[DCOS_OSS-5141](https://jira.mesosphere.com/browse/DCOS_OSS-5141) Pipe output of DEBUG containers to files in the container sandbox instead of to journald.
> Added test for logger behavior given DEBUG class containers.

- Makefile.am
- overlay/agent.cpp
- overlay/agent.hpp
- overlay/agent_metrics.cpp
- overlay/agent_metrics.hpp
- overlay/master.cpp
- overlay/master_metrics.cpp
- overlay/master_metrics.hpp
- overlay/supervisor.hpp
- overlay/supervisor_metrics.cpp
- overlay/supervisor_metrics.hpp
Add overlay metrics to ease detection of common issues users of the overlay module encounter.
[DCOS_OSS-5321](https://jira.mesosphere.com/browse/DCOS_OSS-5321) Add overlay metrics.
> Add overlay metrics.

- logsink/logsink.cpp
- logsink/logsink.hpp
This tweaks the logsink module in a couple small ways:
* The `int_fd` type is preferred when storing file descriptors.
* A namespace closing comment was incorrect.
* A harmless extern defined in the header would allow the module constructor to be called in other code, such as tests.
> Logsink: Minor fixups.

- overlay/master.cpp
- tests/overlay_tests.cpp
In a typical overlay configuration, there are two overlay networks: `dcos` and `dcos6`, and each of them have the save VXLAN VTEP IP addresses. When dropping agent records from the overlay state, deletion from the replicated log succeeds, but deletion from in-memory data structures fails because the same IP address is deleted twice which leads to a Mesos crash and fail-over.
[DCOS_OSS-5597](https://jira.mesosphere.com/browse/DCOS_OSS-5597) Delete each VTEP IP address only once when deleting agent records.
> Delete each VTEP IP address only once when deleting agent records.

- overlay/master.cpp
- tests/overlay_tests.cpp
In a typical overlay configuration, there are two overlay networks: `dcos` and `dcos6`, and each of them have the save VXLAN VTEP IP addresses. When dropping agent records from the overlay state, deletion from the replicated log succeeds, but deletion from in-memory data structures fails because the same IP address is deleted twice which leads to a Mesos crash and fail-over.
This is a back-port of #119 
[DCOS_OSS-5597](https://jira.mesosphere.com/browse/DCOS_OSS-5597) Delete each VTEP IP address only once when deleting agent records.
> [1.13] Delete each VTEP IP address only once when deleting agent records.

- overlay/master.cpp
- tests/overlay_tests.cpp
In a typical overlay configuration, there are two overlay networks: `dcos` and `dcos6`, and each of them have the save VXLAN VTEP IP addresses. When dropping agent records from the overlay state, deletion from the replicated log succeeds, but deletion from in-memory data structures fails because the same IP address is deleted twice which leads to a Mesos crash and fail-over.
This is a back-port of #119 
[DCOS_OSS-5597](https://jira.mesosphere.com/browse/DCOS_OSS-5597) Delete each VTEP IP address only once when deleting agent records.
> [1.12] Delete each VTEP IP address only once when deleting agent records.

- metrics/isolator.cpp
- metrics/isolator.hpp
- tests/metrics_tests.cpp
Ports the metrics isolator to a Windows compatible build.
This is a stop-gap solution until this module will officially be supported on Windows. This is not officially supported by D2iQ but a technology preview.
Removes the support for linux domain sockets on Windows for obvious reasons. It is yet to be determined if our pipeline supports or even mandates named pipes or alike instead.
[DCOS-58008](https://jira.mesosphere.com/browse/DCOS-58008) Port the open source metrics …
> Technology preview: statsd metrics isolator for Windows

- overlay/master.cpp
It is a fix of bug that could lead to double-allocation of the same VTEP IP address to different agents.
[DCOS_OSS-5626](https://jira.mesosphere.com/browse/DCOS_OSS-5626) Mesos overlay master must reserve all VTEP IP addresses of all overlays of all agents upon recovering from the replicated log.
> Reserve all agent VTEP IPs upon recovering from replicated log.

- overlay/master.cpp
It is a fix of bug that could lead to double-allocation of the same VTEP IP address to different agents.
[DCOS_OSS-5626](https://jira.mesosphere.com/browse/DCOS_OSS-5626) Mesos overlay master must reserve all VTEP IP addresses of all overlays of all agents upon recovering from the replicated log.
> [2.0] Reserve all agent VTEP IPs upon recovering from replicated log.

- journald/journald.cpp
- journald/lib_journald.cpp
Fixes linting problem on the use of `NULL` vs. `nullptr`. Updates the newly introduced OS specific build time function-set determination to an inclusive approach. 
No user facing changes were introduced.
> journald logger fixups for linting and build time configuration.

- tests/journald_tests.cpp
Enables tests that don't need Linux on Windows and macOS.
> Updated tests to follow IFDEF inversion in journald logger.

- metrics/isolator.cpp
With the advent of Windows builds, we have to support a stopgap solution that allows builds without TLS for DC/OS. Fixes metrics modules service scheme use when build without TLS.
> Adds support for non TLS builds. 

- Makefile.am
This PR fixes a build failure due to lack of GRPC headers.
[D2IQ-71789](https://jira.mesosphere.com/browse/D2IQ-71789) Mesos module in DC/OS failed to build
> Included GRPC headers to the test build.
